config/routes.rb
Rails.application.routes.draw do
  root 'top#index'
  devise_for :users
  get 'top' => 'top#index'
  get 'shops' => 'shops#index'
  get 'shops/search' => 'shops#search'
  get 'shops/:id' => 'shops#show'
  post 'shops/:shop_id/reviews/create' => 'reviews#create', as: :shop_reviews
  post 'guides' => 'guides#create',as: :guide
  get 'reviews' => 'reviews#new'
  get 'users/:id' => 'users#show'

end

app/models/guide.rb
class Guide < ActiveRecord::Base
end

app/models/review.rb
class Review < ActiveRecord::Base
end

app/models/scraping.rb
class Scraping
 def self.shop_urls
  agent = Mechanize.new
  links = []
  next_url= "http://tabelog.com/rstLst/washoku/"
  while true
    current_page = agent.get(next_url)
    elements = current_page.search('.list-rst__rst-name-wrap p a')
    elements.each do |ele|
     links << ele.get_attribute('href')
    end
    next_link = current_page.at('.page-move__target.page-move__target--next')
    break unless next_link
    next_url = next_link.get_attribute('href')
    break unless next_url
  end

  links.each do |link|
   get_product(link)
  end
 end

 def self.get_product(link)
  agent = Mechanize.new
  page = agent.get(link)
  name= page.at('.clearfix .display-name').inner_text if name= page.at('.clearfix .display-name').inner_text
  text = page.at('#contents-maintext h3').inner_text if text = page.at('#contents-maintext h3').inner_text
  image = page.at('.mainphoto-box img')[:src] if page.at('.mainphoto-box img')
  shop = Shop.where(name: name,text: text, image: image).first_or_initialize
  shop.save
 end
end

app/models/shop.rb
class Shop < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #before_action :authenticate_user!
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/guides_controller.rb
class GuidesController < ApplicationController
  def create
     redirect_to :back
     Guide.create(user_id: current_user.id, shop_id: params[:shop_id], category: params[:category])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
   @review = Review.create(user_id:current_user.id,shop_id:params[:shop_id],reviews:params[:reviews],rate:params[:rate])
  end

end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController

  def index
    @shops = Shop.all
  end

  def search
    @shops = Shop.where('name LIKE ?', "%#{params[:keyword]}%")
  end

  def show
    @shop = Shop.find(params[:id])
    @review = Review.new
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index 
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def br(str) 
    h(str).gsub(/(\r\n?)|(\n)/, "<br />").html_safe 
  end 
end

app/helpers/guides_helper.rb
module GuidesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Washo
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %header#top-head
      .inner
        #mobile-head
          %h1.logo
            %a{href: "/"}
              Washo
          #nav-toggle
            %div
              %span
              %span
              %span
        %nav#global-nav
          %ul
            %li
              %a{:href => "#"} HOME
            %li
              %a{:href => "#"} PRODUCT
            %li
              %a{:href => "#"} WORKS
            %li
              %a{:href => "#"} COMPANY
            %li
              %a{:href => "#"} CONTACT
    = yield

app/views/shops/_shop.html.haml
.popular-shop-block
  .clearfix
    .shop-image
      %img{:height => "220", :src => shop.image}/
    .shop-detail
      .shop-title
        %a{href: "/shops/#{shop.id}"}
          = br(shop.name)
      .shop-description
        = shop.text

app/views/shops/index.html.erb
<div class="contents row" >
<%= render partial: "shop", collection: @shops %>
</div>

app/views/shops/search.html.erb
<div class="contents row" >
<%= render partial: "shop", collection: @shops %>
</div>

app/views/shops/show.html.erb
<div id="contents">
 <h1 class="showpage-shop-title"><%= @shop.name %></h1>
  <div>
    <img src="<%= @shop.image %>" class="photo">
  </div>

  <%= link_to 'Go', guide_path(shop_id: @shop.id, category: 1),method: :post %>
  <%= link_to 'Guide', guide_path(shop_id: @shop.id, category: 0),method: :post %>

  <h3 class="shop"><%= @shop.text %></h3>
  <hr />
  <h2 class="shop">レビュー</h2>
 <div id="review" >
  <li>
   <div class="detail">
    <h3>美味しいお店</h3>
    <h5>ひっそりとした佇まいのお店。暖簾をくぐると大将が...</h5>
   </div>
  </li>
  <li>
   <h3>美味しいお店</h3>
   <div class="detail">
    <h5>ひっそりとした佇まいのお店。暖簾をくぐると大将が...</h5>
   </div>
  </li>
  <li>
   <h3>美味しいお店</h3>
   <div class="detail">
    <h5>ひっそりとした佇まいのお店。暖簾をくぐると大将が...</h5>
   </div>
  </li>
  <h4>もっと見る>></h4>
  <hr />
 <div>
  <% if user_signed_in? %>
  <%= form_for [@shop, @review] do |f| %>
  <h2>レビューを書く</h2>
          <div style="margin: 8px 0">
            <%= f.label :評価, style: { 'margin-right' => 8 } %>
            <%= f.number_field :rate, placeholder: '評価', value: 1, max: 10, min: 1, html: { class: "search__query", style: 'text-align: right;' } %>
          </div>
          <div style="margin: 8px 0">
            <%= f.text_area :reviews, placeholder: 'レビューを書いてね！', style: 'width: 500px;height: 100px;' %>
          </div>
          <div class="row">
            <div class="col10 push1">
              <%= button_tag type: "submit", class: "btn btn--block" do %>
              投稿する<i class="icon-arrow-right"></i>
              <% end %>
            </div>
          </div>
  <% end %>
  <% end %>
 </div>
</div>

app/views/top/index.html.haml
.head-img
  .search-box
    = form_tag 'shops/search',method: :get do
      = text_field_tag :keyword, nil, placeholder: 'free word', class: 'search-text-field' # 初期値がnil、nameがkeyword、classがsearch-text-field
      = image_submit_tag 'search-50.png'
      %br
      = select_tag :language, options_for_select([['English', 'en'], ['日本語', 'ja']]), class: 'search-lang-select'
.popular-shops
  %h2
    人気のお店ランキング

  .popular-shop-block
    .clearfix
      .shop-image
        = image_tag 'washoku.jpg'
      .shop-detail
        .shop-title
          ◯◯店
        .shop-description
          美味しい美味しい美味しい美味しい美味しい美味しい美味しい美味しい美味しい美味しい美味しい美味しい美味しい美味しい美味しい美味しい美味しい美味しい美味しい美味しい

  .popular-shop-block
    .clearfix
      .shop-image
        = image_tag 'washoku.jpg'
      .shop-detail
        .shop-title
          ◯◯店
        .shop-description
          美味しい美味しい美味しい美味しい美味しい美味しい美味しい美味しい美味しい美味しい美味しい美味しい美味しい美味しい美味しい美味しい美味しい美味しい美味しい美味しい

  .popular-shop-block
    .clearfix
      .shop-image
        = image_tag 'washoku.jpg'
      .shop-detail
        .shop-title
          ◯◯店
        .shop-description
          美味しい美味しい美味しい美味しい美味しい美味しい美味しい美味しい美味しい美味しい美味しい美味しい美味しい美味しい美味しい美味しい美味しい美味しい美味しい美味しい

app/views/users/show.html.erb
<div class="user-container">
  <section id="Profile">
    <div id="user" class="text-center">
      <div id="img"></div>
      <div id="name">
        <h1>Maggie Wilson</h1>
      </div>
      <div id="social">
        <a href="#">
          <span class="fa-stack fa-lg">
            <i class="fa fa-circle fa-stack-2x"></i>
            <i class="fa fa-twitter fa-stack-1x"></i>
          </span>
        </a>
        <a href="#">
          <span class="fa-stack fa-lg">
            <i class="fa fa-circle fa-stack-2x"></i>
            <i class="fa fa-facebook-f fa-stack-1x"></i>
          </span>
        </a>
        <a href="#">
          <span class="fa-stack fa-lg">
            <i class="fa fa-circle fa-stack-2x"></i>
            <i class="fa fa-line fa-stack-1x"></i>
          </span>
        </a>
    </div>
    </div>
    <div id="content">
      <div id="navigation">
        <ul role="tablist" class="nav nav-tabs nav-justified">
          <li role="presentation">
            <a href="#about" role="tab" data-toggle="tab">
            <i class="fa fa-user fa-3x">
            </i>
            </a>
          </li>
          <li role="presentation">
            <a href="#skills" role="tab" data-toggle="tab">
            <i class="fa fa-trophy fa-3x">
            </i>
            </a>
          </li>
          <li role="presentation">
            <a href="#contact" role="tab" data-toggle="tab">
            <i class="fa fa-envelope-o fa-3x">
            </i>
            </a>
          </li>
        </ul>
        <div class="tab-content">
          <div id="about" role="tabpanel" class="tab-pane fade">
            <h3>自己紹介</h3>
            <h4>はじめまして</h4>
          </div>
          <div id="go" role="tabpanel" class="tab-pane fade">
            <h3>行きたい</h3>
            <h4>案内したい人一覧</h4>
          </div>
          <div id="guide" role="tabpanel" class="tab-pane fade">
            <h3>案内したい</h3>
            <h4>行きたい人一覧</h4>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>